In [1]:
import numpy as np

In [2]:
my_list1 =  [1, 2, 3, 4]

In [3]:
my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2 = [11, 22, 33, 44]

In [6]:
my_lists = [my_list1, my_list2]

In [7]:
my_array2 = np.array(my_lists)

In [8]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [9]:
my_array2.shape

(2, 4)

In [10]:
my_array2.dtype

dtype('int64')

In [11]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [13]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [14]:
np.empty(5)
np.empty((3,4))

array([[  0.00000000e+000,   0.00000000e+000,   2.17859444e-314,
          2.17828540e-314],
       [  2.17671400e-314,   2.17309371e-314,   2.12356981e-314,
          0.00000000e+000],
       [  2.16879563e-314,   1.33834592e-315,   0.00000000e+000,
          0.00000000e+000]])

In [15]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])