In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [8]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [9]:
A = np.random.randn(10)

A

array([-2.59899073, -0.47606051,  0.51049986,  0.55454824, -0.3773966 ,
       -0.3982968 , -0.49978314, -0.61204264,  0.64650167, -0.02328457])

In [10]:
B = np.random.randn(10)

B

array([-0.55340667, -0.40704152, -0.72070903,  0.18391881, -1.4352216 ,
        0.93162501, -0.77380229, -2.31032569,  2.54965294, -2.45885515])

In [11]:
np.add(A, B)

array([-3.1523974 , -0.88310203, -0.21020916,  0.73846705, -1.8126182 ,
        0.53332822, -1.27358543, -2.92236833,  3.19615461, -2.48213972])

In [ ]:
np.m