In [1]:
import numpy as np

In [4]:
5/2

2.5

In [3]:
from __future__ import division

In [7]:
arr1 = np.array([[1, 2, 3], [8, 9, 10]])
arr1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [8]:
arr1*arr1

array([[  1,   4,   9],
       [ 64,  81, 100]])

In [10]:
arr1-arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
1/arr1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.125     ,  0.11111111,  0.1       ]])

In [12]:
arr1**4

array([[    1,    16,    81],
       [ 4096,  6561, 10000]])